#!/bin/bash

sudo apt install postgresql postgresql-contrib
sudo -u postgres createuser postgres
sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'postgres';"
sudo -u postgres createdb reddit_db
sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE reddit_db TO postgres;"

