#!/usr/bin/env python3.8

import os
import sys

arguments = ["hook-impl", "--config=.pre-commit-config.yaml", "--hook-type=pre-commit"]
arguments.extend(
    ("--hook-dir", os.path.realpath(os.path.dirname(__file__)), "--", *sys.argv[1:])
)

command = ["pre-commit"]
command.extend(arguments)

os.execvp(command[0], command)
